# Numerical Python

In [1]:
import numpy as np

## np.array()

In [2]:
l = [1, 2, 3, 4, 5]
npa = np.array(l)
type(l), type(npa)

(list, numpy.ndarray)

In [3]:
npa.shape

(5,)

In [4]:
l.append('string')
npa = np.array(l)
npa

array(['1', '2', '3', '4', '5', 'string'], dtype='<U21')

In [5]:
l1 = [1, 4, 9, 16]
l

[1, 2, 3, 4, 5, 'string']

In [6]:
l + l1

[1, 2, 3, 4, 5, 'string', 1, 4, 9, 16]

In [7]:
np.array(l + l1)

array(['1', '2', '3', '4', '5', 'string', '1', '4', '9', '16'],
      dtype='<U21')

In [8]:
l + [20] #lists only add on lists

[1, 2, 3, 4, 5, 'string', 20]

In [9]:
l = [[1, 2], [3, 4], [3, 4]]
npa2d = np.array(l)
npa2d

array([[1, 2],
       [3, 4],
       [3, 4]])

In [10]:
npa2d.shape

(3, 2)

In [11]:
npa2d = np.array(l, dtype = 'float')
npa2d

array([[1., 2.],
       [3., 4.],
       [3., 4.]])

In [12]:
npa2d.astype('int')

array([[1, 2],
       [3, 4],
       [3, 4]])

In [13]:
npa2d = npa2d.astype('str')
npa2d

array([['1.0', '2.0'],
       ['3.0', '4.0'],
       ['3.0', '4.0']], dtype='<U32')

In [14]:
npa2d[0][0] + str(1)

'1.01'

## np.nan and np.inf

In [15]:
np.nan == np.nan

False

In [16]:
None == None

True

In [17]:
np.inf == np.inf

True

In [19]:
npa2d = npa2d.astype('float') #string to float to int

In [20]:
npa2d = npa2d.astype('int')

In [21]:
npa2d

array([[1, 2],
       [3, 4],
       [3, 4]])

In [22]:
npa2d = npa2d.astype('float')

In [23]:
npa2d[0][0] = np.nan
npa2d[1][1] = np.inf
npa2d

array([[nan,  2.],
       [ 3., inf],
       [ 3.,  4.]])

In [24]:
np.isnan(npa2d)

array([[ True, False],
       [False, False],
       [False, False]])

In [25]:
np.isinf(npa2d)

array([[False, False],
       [False,  True],
       [False, False]])

In [26]:
flag = np.isnan(npa2d) | np.isinf(npa2d)
flag

array([[ True, False],
       [False,  True],
       [False, False]])

In [27]:
npa2d[flag]

array([nan, inf])

In [28]:
npa2d[flag] = 0
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

## Statistical Operations

In [29]:
# mean, var, std, med

In [30]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [31]:
npa2d.mean()

2.0

In [32]:
npa2d.min()

0.0

In [33]:
npa2d.max()

4.0

In [34]:
npa2d.var()

2.3333333333333335

In [35]:
npa2d.std()

1.5275252316519468

In [36]:
np.median(npa2d)

2.5

## Shape(), Reshape(), Ravel()

In [37]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [38]:
npa2d.shape

(3, 2)

In [39]:
npa2d.reshape(2, 3)

array([[0., 2., 3.],
       [0., 3., 4.]])

In [40]:
npa2d.reshape(1, 6)

array([[0., 2., 3., 0., 3., 4.]])

In [41]:
npa2d.reshape(1, 6).ravel()

array([0., 2., 3., 0., 3., 4.])

In [42]:
npa2d.flatten()

array([0., 2., 3., 0., 3., 4.])

## sequence, repetitions, and random numbers
### arange(), linspace(), random(), zeros(), and ones()

In [43]:
np.arange(1, 5, dtype = 'float')

array([1., 2., 3., 4.])

In [44]:
np.arange(1, 20, 3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [45]:
np.linspace(1, 20, 5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [46]:
np.logspace(1, 50, 10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [47]:
np.zeros([1, 5])

array([[0., 0., 0., 0., 0.]])

In [48]:
np.zeros([1, 2, 3])

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [49]:
np.ones([1, 2])

array([[1., 1.]])

In [50]:
np.tile([1, 2], 3)

array([1, 2, 1, 2, 1, 2])

In [51]:
np.repeat([1, 2], 3)

array([1, 1, 1, 2, 2, 2])

In [52]:
np.random.rand(3, 3)

array([[0.74781346, 0.15954913, 0.21014045],
       [0.95125175, 0.5306067 , 0.78960413],
       [0.86646286, 0.32827976, 0.4932299 ]])

In [53]:
np.random.randint(0, 100, [3, 3])

array([[94, 11, 70],
       [97, 30, 63],
       [18,  8, 51]])

In [54]:
np.random.seed(1)
np.random.randint(0, 100, [3, 3])

array([[37, 12, 72],
       [ 9, 75,  5],
       [79, 64, 16]])

In [56]:
np.unique(npa2d)

array([0., 2., 3., 4.])

In [57]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [58]:
np.unique(npa2d, return_counts= True)

(array([0., 2., 3., 4.]), array([2, 1, 2, 1]))

## where()

In [60]:
arr = np.array([8,94,8,56,1,3,4,5,7])
arr

array([ 8, 94,  8, 56,  1,  3,  4,  5,  7])

In [61]:
np.where(arr>10)

(array([1, 3]),)

In [62]:
index = np.where(arr>10)
arr[index]

array([94, 56])

In [63]:
index = np.where(arr==10)
arr[index]

array([], dtype=int64)

In [64]:
arr>10

array([False,  True, False,  True, False, False, False, False, False])

In [65]:
arr[arr>10]

array([94, 56])

In [66]:
arr.max()

94

In [67]:
arr.argmax()

1

In [68]:
arr.argmin()

4

In [69]:
arr[arr.argmin()]

1

In [70]:
arr.min()

1

## file read and write

In [71]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [72]:
np.savetxt('npa2d.csv', npa2d, delimiter=',')

In [73]:
np.loadtxt('npa2d.csv', delimiter=',')

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [74]:
np.save('data.npy', npa2d)

In [75]:
np.load('data.npy')

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [76]:
arr

array([ 8, 94,  8, 56,  1,  3,  4,  5,  7])

In [77]:
np.savez('both.npz', arr, npa2d)

In [78]:
d = np.load('both.npz')

In [79]:
d.files

['arr_0', 'arr_1']

In [80]:
d[d.files[1]]

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

## Concatenate and Sorting

In [81]:
np.concatenate([npa2d, npa2d], axis = 0)

array([[0., 2.],
       [3., 0.],
       [3., 4.],
       [0., 2.],
       [3., 0.],
       [3., 4.]])

In [82]:
np.concatenate([npa2d, npa2d], axis = 1)

array([[0., 2., 0., 2.],
       [3., 0., 3., 0.],
       [3., 4., 3., 4.]])

In [83]:
np.concatenate([npa2d, arr], axis = 1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [84]:
np.vstack([npa2d, npa2d])

array([[0., 2.],
       [3., 0.],
       [3., 4.],
       [0., 2.],
       [3., 0.],
       [3., 4.]])

In [85]:
np.hstack([npa2d, npa2d])

array([[0., 2., 0., 2.],
       [3., 0., 3., 0.],
       [3., 4., 3., 4.]])

In [87]:
npa = np.hstack([npa2d, npa2d])

In [88]:
npa.sort()
npa

array([[0., 0., 2., 2.],
       [0., 0., 3., 3.],
       [3., 3., 4., 4.]])

In [89]:
npa.sort(axis = 1)
npa

array([[0., 0., 2., 2.],
       [0., 0., 3., 3.],
       [3., 3., 4., 4.]])

## Working with Dates

In [90]:
d = np.datetime64('2020-12-01 23:34:23') #dec 1st
d

numpy.datetime64('2020-12-01T23:34:23')

In [91]:
d + 10 #added in second

numpy.datetime64('2020-12-01T23:34:33')

In [92]:
oneday = np.timedelta64(1, 'D')
oneday

numpy.timedelta64(1,'D')

In [93]:
d + oneday

numpy.datetime64('2020-12-02T23:34:23')

In [94]:
oneminute = np.timedelta64(1, 'm')
oneminute

numpy.timedelta64(1,'m')

In [95]:
d + oneminute

numpy.datetime64('2020-12-01T23:35:23')